export const UI_COPY = {
  graphRelations: {
    nextInTimeline: 'adjacent in timeline',
    latestNodeInDomain: 'latest node in domain',
  },
  graphHome: {
    loading: 'Loading graph...',
    errorLoading: 'Error loading graph model',
  },
  storyNode: {
    moreDetails: 'more details',
    dragChildNodesHint: 'Drag child nodes inside this domain',
    openDetailPageAriaLabel: (title: string) => `Open detail page for ${title}`,
  },
  bioNode: {
    aboutMe: 'about me',
    reset: 'reset',
    fallbackName: 'Haoyang Li',
    fallbackSubtitle: 'Software engineer in the San Francisco Bay Area',
    fallbackContact: 'lihaoyangjingzhou@outlook.com',
    openBioDetailPageAriaLabel: 'Open the bio detail page',
    resetGraphLayoutAriaLabel: 'Reset graph layout',
  },
  nodeDetailPage: {
    backToGraph: 'Back to graph',
    loading: 'Loading node content...',
    errorLoading: 'Error loading node content',
    notFoundTitle: 'Node not found',
    notFoundDescription: (nodeId: string) => `The node "${nodeId}" does not exist in the current graph dataset.`,
    returnToGraph: 'Return to the graph',
    metaLabels: {
      date: 'Date',
      place: 'Place',
      read: 'Read',
      status: 'Status',
    },
    sections: {
      gallery: 'Gallery',
      story: 'Story',
      connectedNodes: 'Click to Explore Connected nodes',
    },
    bioEntry: {
      title: 'Haoyang Li',
      kind: 'BIO',
      fallbackSubtitle: 'Software engineer in the San Francisco Bay Area',
    },
  },
  bioDetailPage: {
    backToGraph: 'Back to graph',
    loading: 'Loading bio content...',
    errorLoading: 'Error loading bio content',
    fallbackEyebrow: 'Bio node',
    fallbackThemeFactLabel: 'Current frame',
    fallbackPathsSectionLabel: 'Click to Explore Paths into the Graph',
    fallbackLinksSectionLabel: 'Elsewhere',
    portraitAlt: (name: string) => `Portrait of ${name}`,
  },
  contentLoaders: {
    failedToLoadBioContentFrom: (url: string) => `Failed to load bio content from ${url}`,
    invalidBioContentPayloadFrom: (url: string) => `Invalid bio content payload from ${url}`,
    failedToLoadContentFor: (nodeId: string, status: number) => `Failed to load content for "${nodeId}": ${status}`,
    failedToLoadGraphModel: (status: number) => `Failed to load graph model: ${status}`,
  },
  nodeEditor: {
    title: 'Node editor',
    subtitle: 'Dev workspace · edit content, preview the article, and write to JSON files.',
    tabs: {
      content: 'Edit',
      json: 'JSON',
      newNode: 'New Node',
      newDomain: 'New Domain',
    },
    common: {
      loading: 'Loading…',
      openNode: 'Open node',
      chooseNode: 'Choose a node…',
      chooseNodeFallback: 'Choose node',
      edit: 'Edit',
      done: 'Done',
      delete: 'Delete',
      cancel: 'Cancel',
      close: 'Close',
      proceed: 'Proceed',
      working: 'Working…',
    },
    sectionEditor: {
      newSectionLabel: 'New section',
      newSectionText: 'Start writing here.',
      syntaxGuideShow: '? Syntax guide',
      syntaxGuideHide: '↑ Hide syntax guide',
      syntaxHintInlineLabel: 'Inline:',
      syntaxHintInlineBody: 'plain text paragraphs',
      syntaxHintMediaLabel: 'Media:',
      syntaxHintMediaBody: 'for links',
      syntaxHintBlocksLabel: 'Blocks:',
      addSection: '+ Add section',
      addSectionTitle: 'Add section at end',
      deleteSectionTitle: 'Delete section',
    },
    status: {
      recoveredDraft: 'Recovered browser draft.',
      savedDraft: 'Saved browser draft.',
      discardedDraft: 'Discarded browser draft.',
      wroteNodeFile: 'Wrote node JSON to file.',
      wroteNodeFileSkipped: (count: number) =>
        `Wrote node JSON to file. Skipped ${count} incomplete connection${count === 1 ? '' : 's'}.`,
      failedWriteNodeFile: 'Failed to write node file.',
      createdNode: (nodeId: string) => `Created node "${nodeId}".`,
      failedCreateNode: 'Failed to create node.',
      createdDomainOpening: (domainId: string) => `Created domain "${domainId}". Opening new node editor...`,
      failedCreateDomain: 'Failed to create domain.',
      deletedDomainReloading: (domainId: string) => `Deleted domain "${domainId}". Reloading editor...`,
      failedDeleteDomain: 'Failed to delete domain.',
    },
    confirmations: {
      titleConfirm: 'Please confirm',
      titleSuccess: 'Action completed',
      titleError: 'Action failed',
      prompt: (actionDescription: string) => `Are you sure you want to ${actionDescription}?`,
      actionCompleted: 'Action completed successfully.',
      actionFailed: 'Action failed.',
      writeChanges: 'write these editor changes to file',
      writeJsonChanges: 'write these JSON edits to file',
      resetDraft: 'reset this draft back to the last saved file version',
      deleteExplicitConnection: 'delete this explicit connection',
      deleteSection: (label: string) => `delete the "${label}" section`,
      deleteDomain: (domainId: string) => `delete the "${domainId}" domain`,
      writingToFile: 'Writing to file…',
      deletingDomain: 'Deleting domain…',
    },
    domainStats: {
      title: 'Domain statistics',
      subtitle: (nodeCount: number, domainCount: number) => `${nodeCount} nodes across ${domainCount} configured domains`,
      summary: (nodeCount: number, domainCount: number) =>
        `Current graph size: ${nodeCount} nodes across ${domainCount} domains.`,
      delete: 'Delete',
      nodeCount: (count: number) => `${count} node${count === 1 ? '' : 's'}`,
    },
    connectedNodes: {
      relationLabelFallback: 'Add a short label for this connection.',
      relationIncompleteFallback: 'Select the other node to complete this connection.',
    },
    contentTab: {
      emptyState: 'Choose a node above to edit its content.',
      chronology: 'Chronology',
      tags: 'Tags',
      tagsPlaceholder: 'tag1, tag2, …',
      header: 'Header',
      title: 'Title',
      subtitle: 'Subtitle',
      summary: 'Summary',
      metadataHero: 'Metadata & hero',
      heroImageSrc: 'Hero image src',
      heroAlt: 'Hero alt',
      heroCaption: 'Hero caption',
      heroPlaceholder: 'assets/hero.jpg',
      fallbackHeroAlt: 'Describe the image',
      metadataFields: {
        date: 'Date',
        place: 'Place',
        readTime: 'Read time',
        status: 'Status',
      },
      connectionDetails: 'Connection details',
      connectionDetailsHint:
        'Timeline links within the same domain are inferred automatically from chronology. Use the connected-node cards on the right to add, remove, and select explicit relations.',
      incompleteConnectionsHint:
        'Incomplete connection drafts stay in the editor, but they will not be saved until both ends are chosen.',
      connectionEditing: 'Editing',
      untitledConnection: 'Untitled connection',
      currentNode: 'Current node',
      currentNodeAnchorHint: (side: string) => `Anchored on the ${side} side for this connection.`,
      otherNode: 'Other node',
      otherNodePlaceholder: 'Search by title, id, subtitle, or domain…',
      otherNodeDirectionFrom: 'This connection points from the current node to the selected node.',
      otherNodeDirectionTo: 'This connection points from the selected node to the current node.',
      kind: 'Kind',
      strength: 'Strength',
      label: 'Label',
      explicitConnectionEmpty:
        'Select an explicit connection card on the right to edit its direction, kind, strength, and label.',
      sidebarHint: 'Edit header, metadata, and hero from this panel. Click any section on the right to edit it.',
      writeToFile: 'Write to file',
      saveDraft: 'Save draft',
      reset: 'Reset',
    },
    jsonTab: {
      emptyState: 'Choose a node above to edit raw JSON.',
      writeToFile: 'Write to file',
      saveDraft: 'Save draft',
    },
    newNodeTab: {
      domain: 'Domain',
      nodeId: 'Node id / filename',
      nodeIdExists: 'This node id already exists.',
      nodeIdInvalid: 'Use lowercase letters, numbers, and single hyphens only.',
      nodeIdPlaceholder: 'my-node-id',
      template: 'Template',
      templatePreviewHint: 'The right panel updates live so you can preview the template before creating the node.',
      kind: 'Kind',
      chronology: 'Chronology',
      title: 'Title',
      subtitle: 'Subtitle',
      summary: 'Summary',
      createNode: 'Create node',
    },
    newDomainTab: {
      infoDomainId: 'Domain id:',
      infoDomainIdDescription: 'internal key, folder name, and URL-safe identifier.',
      infoDisplay: 'Display label:',
      infoDisplayDescription: 'human-readable name shown in the UI.',
      infoCardTag: 'Card tag:',
      infoCardTagDescription: 'short badge text shown on graph cards, usually uppercase.',
      infoSeedAngle: 'Seed angle:',
      infoSeedAngleDescription: 'default angle that places this domain around the graph.',
      domainId: 'Domain id',
      domainIdExists: 'This domain id already exists.',
      domainIdInvalid: 'Use lowercase letters, numbers, and single hyphens only.',
      displayLabel: 'Display label',
      cardTag: 'Card tag',
      cardTagExists: 'This card tag already exists.',
      cardTagHint: 'Keep this short and distinct so graph cards stay easy to scan.',
      seedAngle: 'Seed angle',
      createDomain: 'Create domain',
    },
    rightPanel: {
      articleEditor: 'Article editor',
      livePreview: 'Live preview',
      previewSelectionHint: 'Select a node or template draft to preview.',
      previewEmptyState: 'Choose an existing node or start a new template to see the rendered article here.',
    },
  },
} as const;
