import path from 'node:path';
import { access, readFile } from 'node:fs/promises';
import { writeOutputs } from './write-outputs.mjs';
import { getCentralStay } from './trip-naming.mjs';
import { computeTripData } from './pipeline.mjs';
import { HISTORICAL_HOME_CENTERS } from './photo-trip-corrections.mjs';
import { MAIN_CSV_PATH, PHOTO_CSV_PATH } from './paths.mjs';
import { readCandidates, pruneBakedCandidates } from './trip-candidates.mjs';

const OUTPUT_RELATIVE_DIR = 'public/data/tripdots';

// trip-vlogs.json + trip-vlog-details.json (public/data/tripdots/) are both
// hand-edited directly — not generated by this pipeline at all, since every
// field in them is typed by hand, nothing derived. Split in two so the
// frontend can fetch the lightweight index (vlogId/tripId/lon/lat/title) up
// front to place every pin, and only fetch the heavier details (description/
// url/coverImageUrl, keyed by vlogId) once a pin is actually clicked — see
// content/tripDotsData.ts. trip-vlogs.json is a flat array rather than
// keyed-by-trip-id, since a vlog's `tripId` is optional — a daily-life/
// virtual vlog with no corresponding trip just omits it, and only ever shows
// via the frontend's "All vlogs" toggle rather than a specific trip's
// selection. The only thing worth doing at build time is a sanity check:
// warn (don't fail the build) if an entry's tripId is set but doesn't match
// any current trip (e.g. after retuning the detection algorithm shifts a
// photo-trip's id), or if the two files' vlogIds have drifted apart.
async function validateTripVlogs(outputDir, trips) {
  const readJson = async (fileName) => {
    const raw = await readFile(path.join(outputDir, fileName), 'utf8').catch(() => null);
    if (raw === null) return { data: null, missing: true };
    try {
      return { data: JSON.parse(raw), missing: false };
    } catch (err) {
      console.warn(`${fileName} is not valid JSON: ${err.message}`);
      return { data: null, missing: false };
    }
  };

  const [index, details] = await Promise.all([readJson('trip-vlogs.json'), readJson('trip-vlog-details.json')]);
  if (index.data === null || details.data === null) return;

  const tripIds = new Set(trips.map((trip) => trip.id));
  const indexVlogIds = new Set();
  for (const vlog of index.data) {
    if (vlog.tripId && !tripIds.has(vlog.tripId)) {
      console.warn(
        `trip-vlogs.json references unknown trip id "${vlog.tripId}" (vlogId "${vlog.vlogId}") — no matching trip, this entry will only show via "All vlogs".`,
      );
    }
    indexVlogIds.add(vlog.vlogId);
    if (!details.data[vlog.vlogId]) {
      console.warn(`trip-vlogs.json has vlogId "${vlog.vlogId}" with no matching entry in trip-vlog-details.json.`);
    }
  }
  for (const vlogId of Object.keys(details.data)) {
    if (!indexVlogIds.has(vlogId)) {
      console.warn(`trip-vlog-details.json has vlogId "${vlogId}" with no matching entry in trip-vlogs.json.`);
    }
  }
}

function formatTripDebugRow(trip, getLabel) {
  const startDate = new Date(trip.startTs * 1000).toISOString().slice(0, 10);
  const endDate = new Date(trip.endTs * 1000).toISOString().slice(0, 10);
  const central = getCentralStay(trip);
  return {
    id: trip.id,
    start: startDate,
    end: endDate,
    durationDays: ((trip.endTs - trip.startTs) / 86400).toFixed(1),
    distanceKm: Math.round(trip.totalDistanceKm),
    maxDistFromHomeKm: Math.round(trip.maxDistanceFromHomeKm),
    stays: trip.stays.length,
    place: getLabel(central.lon, central.lat),
  };
}

export async function generateTripDots({ rootDir, debug = false }) {
  const csvPath = MAIN_CSV_PATH;
  const outputDir = path.resolve(rootDir, OUTPUT_RELATIVE_DIR);

  // The raw GPS CSV is deliberately not committed (85MB of personal location
  // history) — only its committed, already-generated output under
  // public/data/tripdots/ ships with the repo. Regeneration is only possible
  // with the source file present locally, so skip it gracefully rather than
  // failing predev/prebuild for anyone (including CI) without a local copy.
  const csvExists = await access(csvPath)
    .then(() => true)
    .catch(() => false);
  if (!csvExists) {
    console.log(`Source CSV not found at ${csvPath} — skipping trip-dots regeneration, keeping committed output as-is.`);
    return { tripCount: null, homeCenterCount: null, skipped: true };
  }

  const { cleanedPoints, homeCenters, classifiedStays, trips, funFacts, getLabel } = await computeTripData({
    csvPath,
    photoCsvPath: PHOTO_CSV_PATH,
  });

  if (debug) {
    console.log(`Home center(s): ${homeCenters.length}`);
    console.table(
      homeCenters.map((home) => ({
        id: home.id,
        label: getLabel(home.lon, home.lat),
        activeStart: new Date(home.activeStart * 1000).toISOString().slice(0, 10),
        activeEnd: new Date(home.activeEnd * 1000).toISOString().slice(0, 10),
      })),
    );
    console.log(`Detected trips: ${trips.length}`);
    console.table(trips.map((trip) => formatTripDebugRow(trip, getLabel)));

    console.log('Fun facts:');
    console.table({
      northmost: { ...funFacts.northmost, label: getLabel(funFacts.northmost.lon, funFacts.northmost.lat) },
      southmost: { ...funFacts.southmost, label: getLabel(funFacts.southmost.lon, funFacts.southmost.lat) },
      highest: funFacts.highest && { ...funFacts.highest, label: getLabel(funFacts.highest.lon, funFacts.highest.lat) },
      lowest: funFacts.lowest && { ...funFacts.lowest, label: getLabel(funFacts.lowest.lon, funFacts.lowest.lat) },
    });
  }

  // A trip id still pending in new-trip-candidates.json (see trip_extract.mjs)
  // may carry a hand-edited title from review — seed trips-meta.json with
  // that instead of write-outputs' plain geocoded default wherever present.
  const candidates = await readCandidates();
  const titleOverrides = new Map(Object.entries(candidates).filter(([, c]) => c.title).map(([id, c]) => [id, c.title]));

  await writeOutputs({
    outputDir,
    trips,
    homeCenters,
    historicalHomeCenters: HISTORICAL_HOME_CENTERS,
    cleanedPoints,
    classifiedStays,
    getLabel,
    funFacts,
    sourceRowCount: cleanedPoints.length,
    titleOverrides,
  });

  const prunedCount = await pruneBakedCandidates(new Set(trips.map((trip) => trip.id)));
  if (prunedCount > 0) console.log(`Baked and cleared ${prunedCount} reviewed candidate(s) from new-trip-candidates.json.`);

  await validateTripVlogs(outputDir, trips);

  return { tripCount: trips.length, homeCenterCount: homeCenters.length };
}
