function buildStringHash(value) {
  let hash = 0x811c9dc5;

  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }

  return (hash >>> 0).toString(16).padStart(8, '0');
}

export function buildGraphLayoutHash(graph) {
  const nodes = Array.isArray(graph?.nodes) ? graph.nodes : [];
  const relations = Array.isArray(graph?.relations) ? graph.relations : [];
  const settings = graph && typeof graph === 'object' ? graph.settings : undefined;

  const payload = JSON.stringify({
    version: 1,
    settings: {
      deriveTemporalRelationsByDomain:
        settings && typeof settings.deriveTemporalRelationsByDomain === 'boolean'
          ? settings.deriveTemporalRelationsByDomain
          : true,
      deriveLatestBioLinksByDomain:
        settings && typeof settings.deriveLatestBioLinksByDomain === 'boolean'
          ? settings.deriveLatestBioLinksByDomain
          : true,
    },
    nodes: nodes
      .filter((node) => node && typeof node.id === 'string')
      .map((node) => ({
        id: node.id,
        kind: node.kind,
        domain: node.domain,
        chronology: node.chronology,
      }))
      .sort((left, right) => left.id.localeCompare(right.id)),
    relations: relations
      .filter((relation) => relation && typeof relation.id === 'string')
      .map((relation) => ({
        id: relation.id,
        from: relation.from,
        to: relation.to,
        kind: relation.kind,
        strength: relation.strength,
      }))
      .sort((left, right) => left.id.localeCompare(right.id)),
  });

  return `graph-${buildStringHash(payload)}`;
}

export function buildGraphLayoutHashModuleSource(graphHash) {
  return `// Generated by scripts/generate_node_index.mjs. Do not edit by hand.\nexport const GRAPH_LAYOUT_HASH = ${JSON.stringify(graphHash)};\n`;
}
